apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: registry-janitor
spec:
  schedule: "* */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: registry
            image: registry:2.7.1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/registry
            - garbage-collect
            - -m
            - /janitor-config/janitor-config.yaml
            volumeMounts:
            - name: storage
              mountPath: "/var/lib/registry"
            - name: config
              mountPath: "/janitor-config"
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: storage
            persistentVolumeClaim:
              claimName: registry-pvc
          - name: config
            configMap:
              name: janitor-configmap
              items:
              - key: "janitor-config.yaml"
                path: "janitor-config.yaml"
