kind: Service
apiVersion: v1
metadata:
  name: registry-service
spec:
  selector:
    app: registry
  ports:
  - name: main
    port: 5000
    targetPort: 5000
  - name: metrics
    port: 5001
    targetPort: 5001
  type: ClusterIP
