apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 2
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2.7.1
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR
          value: "redis"
        - name: REGISTRY_REDIS_ADDR
          value: "redis-service:6379"
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: "/var/lib/registry"
        - name: REGISTRY_HTTP_DEBUG_ADDR
          value: ":5001"
        - name: REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED
          value: "true"
        - name: REGISTRY_HTTP_DEBUG_PROMETHEUS_PATH
          value: /metrics
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/registry-auth/htpasswd"
        volumeMounts:
        - mountPath: "/var/lib/registry"
          name: storage-volume
        - name: auth-volume
          mountPath: "/registry-auth"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /metrics
            port: 5001
          failureThreshold: 1
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 5001
          failureThreshold: 30
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: registry-pvc
      - name: auth-volume
        secret:
          secretName: registry-secret-auth
